services:
  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    container_name: searxng
    volumes:
      - ./deploy/docker/searxng_data:/etc/searxng:rw
    networks:
      - ssmcp
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  ssmcp:
    build:
      context: .
      target: production
    image: ssmcp:latest
    restart: unless-stopped
    container_name: ssmcp
    env_file:
      - .env
    shm_size: 2gb
    ports:
      - '8000:8000'
    volumes:
      - ./deploy/docker/ssmcp:/app/deploy/docker/ssmcp
    networks:
      - ssmcp
    depends_on:
      searxng:
        condition: service_healthy

  # redis:
  #   image: docker.io/redis:8-alpine
  #   restart: unless-stopped
  #   container_name: redis
  #   networks:
  #     - ssmcp
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 15s

  # ssmcp-ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ui
  #   image: ssmcp-ui:latest
  #   restart: unless-stopped
  #   container_name: ssmcp-ui
  #   env_file:
  #     - .env
  #   ports:
  #     - '8081:8080'
  #   networks:
  #     - ssmcp
  #   depends_on:
  #     redis:
  #       condition: service_healthy

networks:
  ssmcp:
    driver: bridge
